name: Build OpenWrt Z8103AX-D

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout
      with:
        ref: z81013axde

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget python3

    - name: Load .config
      run: |
        cp .github/z8103axd.config .config
        make defconfig

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build
      run: |
        make download -j$(nproc) V=s || make download -j1 V=s
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: Z8103AXD-Firmware
        path: bin/targets/
